config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    put '/shipments/:id/receive', to: 'shipments#receive', as: :shipment_receive
    put '/shipments/:id/pick', to: 'shipments#pick', as: :shipment_pick

    get '/orders/to_export', to: 'orders#to_export', as: :orders_to_export
    put '/orders/:id/export', to: 'orders#export', as: :order_export
  end

  namespace :admin do
    resources :reports, only: [:index] do
      collection do
        get :unexported_orders
        post :unexported_orders
      end
    end
  end

  get '/xlsx-export/orders', to: 'orders#export_xlsx', as: :order_export_xlsx
end

app/models/concerns/solidus_wms/configuration.rb
module SolidusWms
  class Configuration < ::Spree::Preferences::Configuration
    attr_accessor :order_xls_export_class
    attr_accessor :order_xls_export_mailer_class
  end
end

app/models/concerns/solidus_wms/order_exported_at.rb
module SolidusWms
  module OrderExportedAt
    extend ActiveSupport::Concern

    included do
      def self.exported
        where.not(exported_at: nil)
      end

      def self.not_exported
        where(exported_at: nil)
      end

      def self.to_export(timestamp)
        not_exported.where(shipment_state: 'ready').where("completed_at <= ?", timestamp)
      end
    end

    def export!
      raise StandardError unless complete?

      touch(:exported_at)
    end

    def exported?
      exported_at.present?
    end
  end
end

app/models/concerns/solidus_wms/shipment_determine_state.rb
module SolidusWms
  module ShipmentDetermineState
    extend ActiveSupport::Concern

    def determine_state(order)
      return 'picked' if state == 'picked'
      return 'received' if state == 'received'

      super
    end
  end
end

app/models/concerns/solidus_wms/shipment_statemachine_transitions.rb
module SolidusWms
  module ShipmentStatemachineTransitions
    extend ActiveSupport::Concern

    included do
      state_machine do
        event :receive do
          transition from: :ready, to: :received
        end

        event :pick do
          transition from: :received, to: :picked
        end

        event :ship do
          reset
          transition from: [:ready], to: :shipped, if: :can_transition_from_ready_to_shipped?
          transition from: [:received], to: :shipped, if: :can_transition_from_received_to_shipped?
          transition from: [:canceled, :picked], to: :shipped
        end

        after_transition to: [:received, :picked, :shipped], do: :update_order_shipment_state
        after_transition to: :received, do: :mark_received
      end
    end

    def can_transition_from_ready_to_shipped?
      !order.exported?
    end

    def can_transition_from_received_to_shipped?
      true
    end

    def mark_received
      touch :received_at
    end

    def update_order_shipment_state
      update!(order)
      order.updater.update
    end
  end
end

app/controllers/concerns/solidus_wms/additional_admin_reports.rb
module SolidusWms
  module AdditionalAdminReports
    extend ActiveSupport::Concern

    def initialize
      super
      ::Spree::Admin::ReportsController.add_available_report!(:unexported_orders)
    end

    def unexported_orders
      params[:q] = {} unless params[:q]

      parsed_completed_at_time_param

      params[:q][:store_id_eq] = current_store.id unless params[:q][:store_id_eq].present?

      params[:q][:s] = 'completed_at desc' unless params[:q][:s].present?

      @search = Spree::Order.complete.not_exported.ransack(params[:q])
      @orders = orders_with_relations.page(params[:page]).per(Spree::Config[:orders_per_page])
      @total_orders = orders_with_relations.count
    end

    private

    def orders_with_relations
      if current_store.use_stock
        @search.result.includes(:line_items, :variants)
      else
        @search.result
      end
    end

    def parsed_completed_at_time_param
      params[:q][:completed_at_gt] =
        begin
          Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day
        rescue
          Time.zone.now.beginning_of_month
        end
    end
  end
end

app/controllers/concerns/solidus_wms/additional_orders_actions.rb
require 'axlsx'

module SolidusWms
  module AdditionalOrdersActions
    extend ActiveSupport::Concern

    included do
      skip_before_action :check_authorization
      before_action :authenticate_basic_auth, only: [:export_xlsx]
    end

    def export_xlsx
      exporter = Wms::OrderExporter.new(Spree::WmsConfig.order_xls_export_class.new)
      recipients = permitted_mailer_params[:recipients]
      exporter.export_xlsx(Wms::AttachmentMailer.new(recipients: recipients))
      render body: nil
    end

    private

    def authenticate_basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV.fetch('HTTP_AUTH_USER') && password == ENV.fetch('HTTP_AUTH_PASS')
      end
    end

    def permitted_mailer_params
      params.permit(recipients: [])
    end
  end
end

app/controllers/concerns/solidus_wms/additional_orders_api_actions.rb
module SolidusWms
  module AdditionalOrdersApiActions
    extend ActiveSupport::Concern

    included do
      skip_before_action :find_order, only: [:to_export]
      skip_around_action :lock_order, only: [:to_export]
    end

    def export
      authorize! :update, @order, params[:token]
      @order.export!
      respond_with(@order, default_template: :show)
    end

    def to_export
      authorize! :index, Spree::Order
      @orders = Spree::Order.by_store(current_store).to_export(params[:completed_before])
      respond_with(@orders, default_template: :to_export)
    end
  end
end

app/controllers/concerns/solidus_wms/additional_shipments_api_actions.rb
module SolidusWms
  module AdditionalShipmentsApiActions
    extend ActiveSupport::Concern

    included do
      alias_method :wms_lock_order, :lock_order

      skip_around_action :lock_order, only: [:pick, :receive]
      before_action :wms_find_shipment, only: [:pick, :receive]
      around_action :wms_lock_order, only: [:pick, :receive]
    end

    def pick
      authorize! :ship, @shipment
      unless @shipment.picked?
        @shipment.pick!
      end
      respond_with(@shipment, default_template: :show)
    end

    def receive
      authorize! :ship, @shipment
      unless @shipment.received?
        @shipment.receive!
      end
      respond_with(@shipment, default_template: :show)
    end

    private

    def wms_find_shipment
      find_shipment
    end
  end
end

app/views/spree/admin/reports/_unexported_order_criteria.html.erb
<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for @search, url: spree.unexported_orders_admin_reports_path do |f| %>
      <div class="row">
        <div class="field-block col-12 col-md-6 col-lg-4 col-xl-3">
          <div class="field">
            <%= label_tag :q_completed_at_gt, Spree.t(:since) %>
            <%= f.text_field :completed_at_gt,
                class: 'datepicker datepicker-from',
                value: datepicker_field_value(params[:q][:completed_at_gt])
            %>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 col-xl-6">
          <div class="row">
            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
                <%= f.text_field :number_cont %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_email_cont, Spree.t(:email) %>
                <%= f.text_field :email_cont %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button Spree.t(:filter_results) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/reports/unexported_orders.html.erb
<% admin_layout "full-width" %>
<% admin_breadcrumb(plural_resource_name(Spree::Order)) %>

<% content_for :page_title do %>
  <%= Spree.t(:unexported_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:date_range) %>
<% end %>

<% content_for :table_filter do %>
  <%= render partial: 'spree/admin/reports/unexported_order_criteria' %>
<% end %>

<% if @orders.any? %>
  <%= paginate @orders, theme: "solidus_admin" %>
  <table class="admin-report" data-hook>
    <thead>
    <tr>
      <th><%= sort_link @search, :completed_at %></th>
      <th><%= sort_link @search, :number %></th>
      <th><%= I18n.t(:state, scope: 'activerecord.attributes.spree/order') %></th>
      <th><%= I18n.t(:shipment_state, scope: 'activerecord.attributes.spree/order') %></th>
      <th><%= I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :total %></th>
      <% if current_store.use_stock %>
        <th> <%= I18n.t(:stock, scope: 'activerecord.attributes.spree/order') %> </th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr class="<%= order.completed_at < 3.days.ago ? 'state-canceled' : '' %>
                 <%= cycle('odd', 'even') %>">
        <td class="align-center">
          <%= l(order.completed_at).to_date %></td>
        <td class="align-center">
          <%= link_to order.number, edit_admin_order_path(order) %></td>
        <td class="align-center">
          <span class="state <%= order.state %>"><%= order.state %></span></td>
        <td class="align-center">
          <span class="state <%= order.shipment_state %>"><%= order.shipment_state %></span></td>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
        </td>
        <td class="align-center">
          <%= order.display_total.to_html %>
        </td>
        <% if current_store.use_stock %>
          <td>
            <% stock = order.stock_available? %>
            <span class="state <%= stock ? 'complete' : 'canceled' %>"> <%= stock ? 'yes' : 'no' %></span>
          </td>
        <% end %>
        <td class='actions align-center'>
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @orders, theme: "solidus_admin" %>
    <p class="text-center"><%= Spree.t(:total_orders) %> <b><%= @total_orders %></b></p>
  </div>
<% end %>